### ISSUE TITLE
Database Naming Consistency

### ISSUE THREAD

**Issue by mageowl** [Kaccana-Bhikkhu/qa-archive#1]
Right now the database is in a odd state. If we are going to have the webpage read directly from the database.json (so we don't have to run so many python scripts), it will work better to use the following properties in JSON keys:
- We should remove any special characters (e.g. ā), because these cause more misspelling, and it makes it harder to type the JSON keys. This **only** applies to the keys, not the values.
- We should remove all spaces from the JSON keys, so that we can use the dot accessor in JavaScript, which improves readability in code.
- We should use a consistent naming system (most likely camelCase), so as to not have to check what the name of the current key is.
- We should decide whether to use tabs or spaces for indents.

### The proposed system will change the following data:
```json
"Tag": {
	"Skillful qualities": {
		"Tag": "Skillful qualities",
		"Pāli": "kusalā dhammā",
		"Full tag": "Skillful qualities",
		"Full Pāli": "kusalā dhammā",
		"#": "",
		"Alt. trans.": [],
		"See also": [],
		"Virtual": true,
		"Subtags": [
			"Eightfold Path",
			"Four Noble Truths",
		],
		"Supertags": [],
		"Copies": 1,
		"Primaries": 0,
		"html file": "skillful-qualities.html",
		"List index": 0
	}
}
```
### into
```json
"tag": {
	"skillfulQualities": {
		"name": "Skillful Qualities",
		"pali": "kusalā dhammā",
		"fullName": "", // Use an empty string to default to the regular name
		"fullPali": "", // Same here
		"#": "", // I don't know what this is supposed to be.
		"altTranslations": [],
		"related": [],
		"virtual": true,
		"subtags": [
			"Eightfold Path",
			"Four Noble Truths"
		],
		"supertags": [],
		"copies": 1,
		"primaries": 0
		// We don't need a html file tag, we can use JavaScript to index this.
		// Again, JS can index the list on the fly.
	}
}

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

The database keys are the way they are since they come directly from the AP
QA Archive spreadsheet. The spreadsheet is designed to be easy for humans
(our future volunteers) to use. Also, I've already got my code working with
the current database keys.

How about I write a converter that runs after my current code that switches
the database keys to javascript-friendly values? Please let me know.

All good wishes,
 - Kaccāna Bhikkhu

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

As for your comments about the tag database keys, it can be helpful to look
at the tag/subtag hierarchy page
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/indexes/AllTags.html>
to
see how the keys are used.

"#": "", // I don't know what this is supposed to be.

Some lists are numbered (Noble Eightfold Path), some aren't (Noble
Truth of Suffering). This is a string because at least one list item:
3,4 . Conscience and prudence
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/conscience-and-prudence.html>
[hiri-otappa]

needs a double count to make all Seven Treasures count. (Ajahn Pasanno
invariably talks about these as a pair, so splitting them into two tags
doesn't make sense.)

I can bag the html file tag if you like.

All good wishes,
 - Kaccāna Bhikkhu

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

Also sometimes, some of the list items count and some don't. For example:

Three characteristics
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/three-characteristics.html>
 (1)

1. Impermanence
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/impermanence.html>
(4)
[anicca]

2. Suffering
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/suffering.html>
(2)
[dukkha]

3. Not-self
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/not-self.html>
(13)
[anatta]

Emptiness
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/emptiness.html>
(1)
[suññatā]

Suchness
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/suchness.html> (1)
[tathatā]

Not-made-of-that
<https://kaccana-bhikkhu.github.io/qa-archive/prototype/tags/not-made-of-that.html>
 [atammayatā]

The first three items are a classical list. The latter three were added by
Ajahn Buddhadasa in the 20th Century. This is a convenient place to put
them in the tag hierarchy, but readers would get confused if we say "Three
characteristics" and count to six!

All good wishes,
 - Kaccāna Bhikkhu

**Comment by Kaccana-Bhikkhu** [comment]
I created the camelCaseJSON branch and added a quick function at the end of ParseCSV to modify all database keys. The function I grabbed from the internet (ParseCSV.py / CamelCase) doesn't quite work, so I added a few ugly bits to it. I replaced '#' with 'Number'.

Please take a look at Database.json and see if the keys work for you. I'd like to keep a simple relationship between the spreadsheet headings and the Database.json keys if possible. If you would like me to expand abbreviations ('Alt. Trans.' -> 'alternativeTranslations', it would be best to do that in the source spreadsheet.

This breaks all downstream code, so let's decide on the database keys before merging it back to the main branch. It's time for me to rest now.

All good wishes,
 - Kaccāna Bhikkhu

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

Contemplating the situation, I'd rather not make massive changes to Prototype.py to change all the key names. Why don't we use two database files with essentially the same information but different keys. The spreadsheet database will use keys that match the spreadsheet and the optimized database will use keys suitable for Javascript dot notation.

I've made the branch doubleDatabase to demonstrate this concept. Please let me know your thoughts. In any case, I don't have too many programming hours left before Winter Retreat begins. You are totally welcome to wait until April to do any more on the project if you like.

All good wishes,
 - Kaccāna Bhikkhu

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

doubleDatabase now works reasonably well to camel case all the keys. There are probably many other ways to optimize the database for use with Javascript (I've written about 12 lines of Javascript in my life), and we can now add these optimizations to the OptimizeDatabase.py module without breaking Prototype.py. 

Spreadsheet database - prototype/SpreadsheetDatabase.json
Optimized database - Database.json

Please feel free to merge with main if you like or continue the discussion if you have a better idea. Not so many hours left until I turn into a pumpkin!

All good wishes,
 - Kaccāna Bhikkhu

**Comment by mageowl** [comment]
I would like to take a stab at making a converter, if you wouldn't mind. I
don't often use python, so it would be a welcome challenge.

Thanks and Happy New Year!

**Comment by Kaccana-Bhikkhu** [comment]
Dear Owen,

If you're up for writing a converter, that would be great! I've merged the doubleDatabase branch with main so there are now two databases as described above. I removed all key conversion code from OptimizeDatabase.py so it's a blank slate for you to work with. None of my code depends on the behaviour of OptimizeDatabase.py, so you can do whatever works best for the Javascript website.

`python QAarchive.py OptimizeDatabase`

runs only this module on the spreadsheet database stored at prototype/SpreadsheetDatabase.json for faster testing cycles.

Look at the old doubleDatabase branch if you want to see my attempt to recursively convert database keys. The following code borrowed from the Django slugify function robustly eliminates diacritics:

```
import unicodedata
text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('ascii')
```
And a very happy New Year to you as well!
 - Kaccāna Bhikkhu

**Comment by mageowl** [comment]
This is now fixed by the new code in OptimizeDatabase.py.
